
platform :ios, '11.0'

target 'LOTs' do

  use_frameworks!
  
  pod 'SwiftLint'
  pod 'iOSDropDown'
  pod 'DatePickerDialog'
  pod 'Firebase/Auth'
  pod 'Firebase/Core'
  pod 'Firebase/Storage'
  pod 'Firebase/Database'
  pod 'McPicker', '~> 2.0.0'
  pod 'FBSDKLoginKit'
  pod 'FBSDKCoreKit'
  pod 'Bolts'

end
